<?php

namespace PiBundle\Repository;

/**
 * DemandeEmpruntRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeEmpruntRepository extends \Doctrine\ORM\EntityRepository
{
}
