<?php

namespace PiBundle\Repository;

/**
 * demandesponsoringRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class demandesponsoringRepository extends \Doctrine\ORM\EntityRepository
{
}
