<?php

namespace PiBundle\Repository;

/**
 * empreintRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class empreintRepository extends \Doctrine\ORM\EntityRepository
{
}
