<?php

namespace PiBundle\Repository;

/**
 * EvenementEvaluationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvenementEvaluationRepository extends \Doctrine\ORM\EntityRepository
{
}
