<?php

namespace PiBundle\Repository;

/**
 * ExposeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExposeRepository extends \Doctrine\ORM\EntityRepository
{
}
