<?php

namespace PiBundle\Repository;

/**
 * F_sujetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class F_sujetRepository extends \Doctrine\ORM\EntityRepository
{
}
