<?php

namespace PiBundle\Repository;

/**
 * LCommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LCommentaireRepository extends \Doctrine\ORM\EntityRepository
{
}
