<?php

namespace PiBundle\Repository;

/**
 * offresponsoringRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class offresponsoringRepository extends \Doctrine\ORM\EntityRepository
{
}
