<?php

namespace PiBundle\Repository;

/**
 * PaiementEspeceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaiementEspeceRepository extends \Doctrine\ORM\EntityRepository
{
}
