<?php

namespace PiBundle\Repository;

/**
 * PaiementCarteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaiementCarteRepository extends \Doctrine\ORM\EntityRepository
{
}
