<?php

namespace PiBundle\Repository;

/**
 * SignalcommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SignalcommentaireRepository extends \Doctrine\ORM\EntityRepository
{
}
